package automatl.juras.protocol.product

import automatl.juras.protocol.MachineCatalog
import automatl.juras.protocol.Temperature

/**
 * All per-model data for the Jura E6 / EF1030, derived from protocol reverse
 * engineering and hardware verification. This is the single source of truth for
 * EF1030-specific products, alert bits, brew-state captions, and maintenance fields.
 */
val Ef1030Catalog: MachineCatalog = MachineCatalog(
    modelId = "EF1030",

    // ── Products ─────────────────────────────────────────────────────────────
    products = listOf(
        Product(
            code = 0x02, name = "Espresso", kind = ProductKind.COFFEE,
            strength = Range(default = 8, min = 1, max = 10, step = 1),
            water = Range(default = 45, min = 15, max = 80, step = 5),
            defaultTemperature = Temperature.HIGH,
        ),
        Product(
            code = 0x03, name = "Coffee", kind = ProductKind.COFFEE,
            strength = Range(default = 5, min = 1, max = 10, step = 1),
            water = Range(default = 100, min = 25, max = 240, step = 5),
            defaultTemperature = Temperature.NORMAL,
        ),
        Product(
            code = 0x04, name = "Cappuccino", kind = ProductKind.COFFEE_MILK,
            strength = Range(default = 8, min = 1, max = 10, step = 1),
            water = Range(default = 60, min = 25, max = 240, step = 5),
            milk = Range(default = 12, min = 1, max = 45, step = 1),
            defaultTemperature = Temperature.NORMAL,
        ),
        Product(
            code = 0x06, name = "Espresso Macchiato", kind = ProductKind.COFFEE_MILK,
            strength = Range(default = 8, min = 1, max = 10, step = 1),
            water = Range(default = 25, min = 15, max = 80, step = 5),
            milk = Range(default = 3, min = 1, max = 45, step = 1),
            defaultTemperature = Temperature.HIGH,
        ),
        Product(
            code = 0x28, name = "Caffé Barista", kind = ProductKind.COFFEE,
            strength = Range(default = 6, min = 1, max = 10, step = 1),
            water = Range(default = 60, min = 25, max = 240, step = 5),
            bypass = Range(default = 40, min = 0, max = 240, step = 5),
            defaultTemperature = Temperature.NORMAL,
        ),
        Product(
            code = 0x29, name = "Barista Lungo", kind = ProductKind.COFFEE,
            strength = Range(default = 7, min = 1, max = 10, step = 1),
            water = Range(default = 120, min = 25, max = 240, step = 5),
            bypass = Range(default = 100, min = 0, max = 240, step = 5),
            defaultTemperature = Temperature.NORMAL,
        ),
        Product(
            code = 0x08, name = "Milk Foam", kind = ProductKind.MILK,
            milk = Range(default = 22, min = 1, max = 45, step = 1),
        ),
        Product(
            code = 0x0D, name = "Hot Water", kind = ProductKind.WATER,
            water = Range(default = 220, min = 25, max = 300, step = 5),
            defaultTemperature = Temperature.NORMAL,
        ),
        Product(
            code = 0x31, name = "2 Espressi", kind = ProductKind.COFFEE,
            water = Range(default = 45, min = 15, max = 80, step = 5),
            defaultTemperature = Temperature.HIGH,
        ),
        Product(
            code = 0x36, name = "2 Coffee", kind = ProductKind.COFFEE,
            water = Range(default = 100, min = 25, max = 240, step = 5),
            defaultTemperature = Temperature.NORMAL,
        ),
    ),

    // ── Alert bits (`@TF:` status payload, 7-byte word, MSB-first per byte) ──
    alertBits = mapOf(
        0 to "Insert tray",
        1 to "Fill water",
        2 to "Empty grounds",
        3 to "Empty tray",
        4 to "Insert coffee bin",
        5 to "Outlet missing",
        6 to "Rear cover missing",
        7 to "Milk alert",
        8 to "Fill system",
        9 to "System filling",
        10 to "No beans",
        11 to "Welcome",
        12 to "Heating up",
        13 to "Coffee ready",
        14 to "No milk (sensor)",
        15 to "Milk sensor error",
        16 to "No signal (milk sensor)",
        17 to "Please wait",
        18 to "Coffee rinsing",
        19 to "Ventilation closed",
        20 to "Close powder cover",
        21 to "Fill powder",
        22 to "System emptying",
        23 to "Not enough powder",
        24 to "Remove water tank",
        25 to "Press rinse",
        26 to "Goodbye",
        27 to "Periphery alert",
        28 to "Powder product",
        29 to "Program-mode status",
        30 to "Error status",
        31 to "Enjoy product",
        32 to "Filter alert",
        33 to "Descaling alert",
        34 to "Cleaning alert",
        35 to "Cappu rinse alert",
        36 to "Energy save",
        37 to "Active RF filter",
        38 to "Remote screen",
        39 to "Locked keys",
        40 to "Close tap",
        41 to "Cappu clean alert",
        42 to "Info: cappu clean alert",
        43 to "Info: coffee clean alert",
        44 to "Info: descale alert",
        45 to "Info: filter used up",
        46 to "Steam ready",
        47 to "Switch-off delay active",
        48 to "Close front cover",
        49 to "Left bean alert",
        50 to "Right bean alert",
        53 to "Empty grounds (RTC)",
        54 to "ML/OZ status",
    ),

    // ── Brew progress state captions (`@TV:` byte 0) ─────────────────────────
    brewStateNames = mapOf(
        0x01 to "Insert tray",
        0x02 to "Fill water tank",
        0x03 to "Empty grounds",
        0x04 to "Empty tray",
        0x08 to "Insert grounds box",
        0x09 to "Close nozzle cover",
        0x0A to "Close bean cover",
        0x0B to "Cappu rinse finished",
        0x0C to "Close tap",
        0x0D to "Open tap",
        0x0E to "Alert",
        0x0F to "Close powder cover",
        0x10 to "Add ground coffee",
        0x11 to "Filling system",
        0x12 to "Emptying system",
        0x13 to "Add beans",
        0x14 to "Not enough powder",
        0x15 to "Please wait",
        0x16 to "Remove water tank",
        0x20 to "Starting up",
        0x21 to "Heating up",
        0x22 to "Press button",
        0x23 to "Rinsing",
        0x24 to "Coffee ready",
        0x25 to "Shutting down",
        0x26 to "Press rinse",
        0x2D to "No milk",
        0x2E to "Milk error",
        0x2F to "No milk signal",
        0x39 to "Grinding", // observed on hardware; not in formal spec
        0x3E to "Enjoy",
        0x40 to "Fill water tank", // observed on hardware; not in formal spec
        0x4A to "Cappu clean requested",
        0x50 to "Descale: start",
        0x51 to "Descale: prepare materials",
        0x52 to "Descale: empty tray",
        0x53 to "Descale: add fluid",
        0x54 to "Descaling",
        0x55 to "Rinse water tank",
        0x56 to "Descaling finished",
        0x5A to "Connect milk tube",
        0x5C to "Filter used up",
        0x5D to "Filter locked",
        0x60 to "Filter rinse: start",
        0x61 to "Filter rinse: prepare materials",
        0x62 to "Filter rinse: change",
        0x63 to "Filter rinsing",
        0x65 to "Filter rinse finished",
        0x66 to "Remove filter",
        0x67 to "Insert filter",
        0x70 to "Cleaning: start",
        0x71 to "Cleaning: prepare materials",
        0x72 to "Cleaning: empty tray",
        0x73 to "Cleaning: press button",
        0x74 to "Cleaning",
        0x75 to "Cleaning: add tablet",
        0x76 to "Cleaning finished",
        0x90 to "Cappu clean: start",
        0x91 to "Cappu clean: prepare materials",
        0x92 to "Cappu clean: add cleaner",
        0x93 to "Cappu cleaning",
        0x94 to "Cappu clean: add water",
        0x95 to "Cappu clean finished",
        0x9A to "Cappu rinsing",
        0xA1 to "Set hot-water nozzle",
        0xA2 to "Set milk nozzle",
        0xA3 to "Set nozzle to milk position",
        0xA4 to "Set nozzle to foam position",
        0xC7 to "Long-press saved",
        0xC9 to "Enough milk/water/coffee",
        0xE1 to "Warning",
        0xE2 to "Action required",
        0xE3 to "Info",
        0xE4 to "Filter error",
        0xE5 to "Filter thanks",
        0xE6 to "Too hot",
        0xEF to "Wi-Fi confirmation",
        0xFF to "Programming mode",
    ),

    // ── Dispensing states (show live water progress, not a caption) ───────────
    dispensingStates = setOf(0x34, 0x37, 0x3C, 0x41),

    // ── Maintenance fields (positional order in the machine's reply) ──────────
    maintenanceStatusFields = listOf("Cleaning", "Filter change", "Descaling"),
    maintenanceCounterFields = listOf(
        "Cleaning", "Filter change", "Descaling",
        "Cappu rinse", "Coffee rinse", "Cappu clean",
    ),
)
